# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_entry_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='site_url',
            field=models.URLField(blank=True),
        ),
    ]
