# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180108_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='nut_graph',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
