# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_entry_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='poster',
        ),
    ]
