# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_entry_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='site_url',
            new_name='project_url',
        ),
    ]
