# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('main', '0007_auto_20180109_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='nut_graph',
        ),
        migrations.AddField(
            model_name='entry',
            name='infosheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
