# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180111_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='body',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='entry',
            name='release_date',
            field=models.DateField(help_text='Format YYYY-MM-DD'),
        ),
    ]
