# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('main', '0015_auto_20180126_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='poster',
            field=models.ForeignKey(blank=True, help_text='Dimension 1110px by 540px. Format: PNG or JPG.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='entry',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='Dimension 600px by 315px. Format: PNG or JPG.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='infosheet',
            field=models.ForeignKey(blank=True, help_text='PDF information sheet for printing, if available.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='overview',
            field=models.CharField(blank=True, help_text="A blurb highlighting the project's purpose and effort. Think of it as an elevator pitch", max_length=255),
        ),
        migrations.AlterField(
            model_name='entry',
            name='project_url',
            field=models.URLField(blank=True, help_text='URL of this project, if available.'),
        ),
    ]
