# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180126_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='affiliation',
            field=models.CharField(blank=True, help_text='What department is this project for?', max_length=255),
        ),
    ]
