# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-01 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_textualindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='feature_blurb',
            field=models.CharField(blank=True, help_text='A very short blurb on this entry for the feature carousel', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='feature_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='affiliation',
            field=models.CharField(blank=True, help_text='Which department is this project for?', max_length=255),
        ),
    ]
