# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180202_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='discipline',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='main.Discipline'),
        ),
    ]
