# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 20:31
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180212_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='affiliation',
        ),
        migrations.AlterField(
            model_name='entry',
            name='discipline',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Which discipline is this project for?', to='main.Discipline'),
        ),
    ]
