# Generated by Django 2.2.24 on 2021-09-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210913_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='revision_date',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD. This applies only to a project revision, a MOOC relaunch, or an institute rerun.', null=True),
        ),
    ]
