# Generated by Django 2.2.24 on 2021-11-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210930_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='feature_slot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
