# Generated by Django 2.2.24 on 2021-11-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_entry_feature_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='feature_blurb',
            field=models.CharField(blank=True, help_text='A very short blurb on this entry for the feature carousel.', max_length=255, null=True),
        )
    ]
