# Generated by Django 2.2.25 on 2021-12-14 19:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20211113_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(help_text='Example: Literature', max_length=255),
        ),
        migrations.AlterField(
            model_name='entry',
            name='award_type',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='For project or program that received grants from the Provost office.', to='main.AwardType'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='The main descriptive text of this Portfolio entry page.'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='discipline',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Which academic discipline is this project for?', to='main.Discipline'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='gallery_image_one',
            field=models.ForeignKey(blank=True, help_text='Minimum width 800px. Format: PNG or JPG.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='gallery_image_three',
            field=models.ForeignKey(blank=True, help_text='Minimum width 800px. Format: PNG or JPG.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='gallery_image_two',
            field=models.ForeignKey(blank=True, help_text='Minimum width 800px. Format: PNG or JPG.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='overview',
            field=models.CharField(blank=True, help_text="A highlight of the entry's purpose and effort, a tagline, or the main takeaway from the project. Maximum 255 characters.", max_length=255),
        ),
        migrations.AlterField(
            model_name='entry',
            name='poster',
            field=models.ForeignKey(blank=True, help_text='Minimum 1140px-width by 530px-height. Format: PNG or JPG.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='project_type',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='SKIP THIS!', to='main.ProjectType'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='project_url',
            field=models.URLField(blank=True, help_text='URL for the project or program, at the CTL or elsewhere. Example: https://mediathread.ctl.columbia.edu'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='release_date',
            field=models.DateField(help_text='Format YYYY-MM-DD. Date of project first release.'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='1200px-width by 630px-height. Acceptable:  600px width by 315px height. Format: PNG or JPG.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='affiliation',
            field=models.CharField(help_text="Faculty partner's department", max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='full_title',
            field=models.TextField(blank=True, help_text='Example: Dewitt Clinton Professor Emeritus of History'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='headshot',
            field=models.ForeignKey(blank=True, help_text='Minimum 300px by 300px. Format: PNG or JPG.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(help_text='Full name. Example: Eric Foner', max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='short_title',
            field=models.CharField(help_text='Example: Professor, Librarian, Lecturer', max_length=255),
        ),
    ]
