# Generated by Django 2.2.27 on 2022-03-29 17:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20211214_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='sort_order',
        ),
        migrations.CreateModel(
            name='OrderedPartnerSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_partners', to='main.Entry')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='main.Partner')),
            ],
            options={
                'unique_together': {('page', 'partner')},
            },
        ),
    ]
