# Generated by Django 2.2.27 on 2022-03-29 16:43

from django.db import migrations


def migrate_partners(apps, schema_editor):
    Entry = apps.get_model('main', 'Entry')
    OrderedPartnerSnippet = apps.get_model('main', 'OrderedPartnerSnippet')

    for entry in Entry.objects.all():
        for p in entry.partners.all():
            pe = OrderedPartnerSnippet(page=entry, partner=p)
            pe.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20220329_1308'),
    ]

    operations = [
        migrations.RunPython(migrate_partners)
    ]
