# Generated by Django 2.2.27 on 2022-03-31 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20220329_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedpartnersnippet',
            options={'ordering': ['sort_order']},
        ),
    ]
