# Generated by Django 2.2.27 on 2022-03-31 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20220331_1633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderedpartnersnippet',
            unique_together=set(),
        ),
    ]
